// flow-typed signature: a6e25d30cde50177908d537678e39fb2
// flow-typed version: <<STUB>>/@turf/bearing_v^3.7.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bearing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bearing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/bearing/bench' {
  declare module.exports: any;
}

declare module '@turf/bearing/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/bearing/bench.js' {
  declare module.exports: $Exports<'@turf/bearing/bench'>;
}
declare module '@turf/bearing/index' {
  declare module.exports: $Exports<'@turf/bearing'>;
}
declare module '@turf/bearing/index.js' {
  declare module.exports: $Exports<'@turf/bearing'>;
}
declare module '@turf/bearing/test.js' {
  declare module.exports: $Exports<'@turf/bearing/test'>;
}
