// flow-typed signature: 1e610f5cdfb6996f3d154b911378acd7
// flow-typed version: <<STUB>>/@turf/destination_v^3.7.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/destination'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/destination' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/destination/bench' {
  declare module.exports: any;
}

declare module '@turf/destination/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/destination/bench.js' {
  declare module.exports: $Exports<'@turf/destination/bench'>;
}
declare module '@turf/destination/index' {
  declare module.exports: $Exports<'@turf/destination'>;
}
declare module '@turf/destination/index.js' {
  declare module.exports: $Exports<'@turf/destination'>;
}
declare module '@turf/destination/test.js' {
  declare module.exports: $Exports<'@turf/destination/test'>;
}
