// flow-typed signature: fe578d4c7eafe2aeed8e1c8c9d7f36ec
// flow-typed version: <<STUB>>/@turf/inside_v^3.7.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/inside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/inside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/inside/bench' {
  declare module.exports: any;
}

declare module '@turf/inside/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/inside/bench.js' {
  declare module.exports: $Exports<'@turf/inside/bench'>;
}
declare module '@turf/inside/index' {
  declare module.exports: $Exports<'@turf/inside'>;
}
declare module '@turf/inside/index.js' {
  declare module.exports: $Exports<'@turf/inside'>;
}
declare module '@turf/inside/test.js' {
  declare module.exports: $Exports<'@turf/inside/test'>;
}
