// flow-typed signature: 03f7e817d81b0d97e79130bf10d808c4
// flow-typed version: <<STUB>>/@turf/line-distance_v^3.7.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/line-distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/line-distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/line-distance/bench' {
  declare module.exports: any;
}

declare module '@turf/line-distance/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/line-distance/bench.js' {
  declare module.exports: $Exports<'@turf/line-distance/bench'>;
}
declare module '@turf/line-distance/index' {
  declare module.exports: $Exports<'@turf/line-distance'>;
}
declare module '@turf/line-distance/index.js' {
  declare module.exports: $Exports<'@turf/line-distance'>;
}
declare module '@turf/line-distance/test.js' {
  declare module.exports: $Exports<'@turf/line-distance/test'>;
}
