// flow-typed signature: 325900d60c772be72f8a9abcac266dfa
// flow-typed version: <<STUB>>/@turf/line-slice_v^3.7.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/line-slice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/line-slice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/line-slice/bench' {
  declare module.exports: any;
}

declare module '@turf/line-slice/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/line-slice/bench.js' {
  declare module.exports: $Exports<'@turf/line-slice/bench'>;
}
declare module '@turf/line-slice/index' {
  declare module.exports: $Exports<'@turf/line-slice'>;
}
declare module '@turf/line-slice/index.js' {
  declare module.exports: $Exports<'@turf/line-slice'>;
}
declare module '@turf/line-slice/test.js' {
  declare module.exports: $Exports<'@turf/line-slice/test'>;
}
