// flow-typed signature: 5a2ac652b0b3efa642e6b44f50cd8c2a
// flow-typed version: <<STUB>>/crc_v^3.4.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crc/lib/crc1' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_ccitt' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_kermit' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_modbus' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16_xmodem' {
  declare module.exports: any;
}

declare module 'crc/lib/crc16' {
  declare module.exports: any;
}

declare module 'crc/lib/crc24' {
  declare module.exports: any;
}

declare module 'crc/lib/crc32' {
  declare module.exports: any;
}

declare module 'crc/lib/crc8_1wire' {
  declare module.exports: any;
}

declare module 'crc/lib/crc8' {
  declare module.exports: any;
}

declare module 'crc/lib/create_buffer' {
  declare module.exports: any;
}

declare module 'crc/lib/define_crc' {
  declare module.exports: any;
}

declare module 'crc/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crc/lib/crc1.js' {
  declare module.exports: $Exports<'crc/lib/crc1'>;
}
declare module 'crc/lib/crc16_ccitt.js' {
  declare module.exports: $Exports<'crc/lib/crc16_ccitt'>;
}
declare module 'crc/lib/crc16_kermit.js' {
  declare module.exports: $Exports<'crc/lib/crc16_kermit'>;
}
declare module 'crc/lib/crc16_modbus.js' {
  declare module.exports: $Exports<'crc/lib/crc16_modbus'>;
}
declare module 'crc/lib/crc16_xmodem.js' {
  declare module.exports: $Exports<'crc/lib/crc16_xmodem'>;
}
declare module 'crc/lib/crc16.js' {
  declare module.exports: $Exports<'crc/lib/crc16'>;
}
declare module 'crc/lib/crc24.js' {
  declare module.exports: $Exports<'crc/lib/crc24'>;
}
declare module 'crc/lib/crc32.js' {
  declare module.exports: $Exports<'crc/lib/crc32'>;
}
declare module 'crc/lib/crc8_1wire.js' {
  declare module.exports: $Exports<'crc/lib/crc8_1wire'>;
}
declare module 'crc/lib/crc8.js' {
  declare module.exports: $Exports<'crc/lib/crc8'>;
}
declare module 'crc/lib/create_buffer.js' {
  declare module.exports: $Exports<'crc/lib/create_buffer'>;
}
declare module 'crc/lib/define_crc.js' {
  declare module.exports: $Exports<'crc/lib/define_crc'>;
}
declare module 'crc/lib/index.js' {
  declare module.exports: $Exports<'crc/lib/index'>;
}
