// flow-typed signature: a63ba3f40f6b8a721938f5cf8d32c43d
// flow-typed version: <<STUB>>/d3-format_v^1.0.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-format/build/d3-format' {
  declare module.exports: any;
}

declare module 'd3-format/build/d3-format.min' {
  declare module.exports: any;
}

declare module 'd3-format/src/defaultLocale' {
  declare module.exports: any;
}

declare module 'd3-format/src/exponent' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatDecimal' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatDefault' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatGroup' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatPrefixAuto' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatRounded' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatSpecifier' {
  declare module.exports: any;
}

declare module 'd3-format/src/formatTypes' {
  declare module.exports: any;
}

declare module 'd3-format/src/locale' {
  declare module.exports: any;
}

declare module 'd3-format/src/precisionFixed' {
  declare module.exports: any;
}

declare module 'd3-format/src/precisionPrefix' {
  declare module.exports: any;
}

declare module 'd3-format/src/precisionRound' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-format/build/d3-format.js' {
  declare module.exports: $Exports<'d3-format/build/d3-format'>;
}
declare module 'd3-format/build/d3-format.min.js' {
  declare module.exports: $Exports<'d3-format/build/d3-format.min'>;
}
declare module 'd3-format/index' {
  declare module.exports: $Exports<'d3-format'>;
}
declare module 'd3-format/index.js' {
  declare module.exports: $Exports<'d3-format'>;
}
declare module 'd3-format/src/defaultLocale.js' {
  declare module.exports: $Exports<'d3-format/src/defaultLocale'>;
}
declare module 'd3-format/src/exponent.js' {
  declare module.exports: $Exports<'d3-format/src/exponent'>;
}
declare module 'd3-format/src/formatDecimal.js' {
  declare module.exports: $Exports<'d3-format/src/formatDecimal'>;
}
declare module 'd3-format/src/formatDefault.js' {
  declare module.exports: $Exports<'d3-format/src/formatDefault'>;
}
declare module 'd3-format/src/formatGroup.js' {
  declare module.exports: $Exports<'d3-format/src/formatGroup'>;
}
declare module 'd3-format/src/formatPrefixAuto.js' {
  declare module.exports: $Exports<'d3-format/src/formatPrefixAuto'>;
}
declare module 'd3-format/src/formatRounded.js' {
  declare module.exports: $Exports<'d3-format/src/formatRounded'>;
}
declare module 'd3-format/src/formatSpecifier.js' {
  declare module.exports: $Exports<'d3-format/src/formatSpecifier'>;
}
declare module 'd3-format/src/formatTypes.js' {
  declare module.exports: $Exports<'d3-format/src/formatTypes'>;
}
declare module 'd3-format/src/locale.js' {
  declare module.exports: $Exports<'d3-format/src/locale'>;
}
declare module 'd3-format/src/precisionFixed.js' {
  declare module.exports: $Exports<'d3-format/src/precisionFixed'>;
}
declare module 'd3-format/src/precisionPrefix.js' {
  declare module.exports: $Exports<'d3-format/src/precisionPrefix'>;
}
declare module 'd3-format/src/precisionRound.js' {
  declare module.exports: $Exports<'d3-format/src/precisionRound'>;
}
