// flow-typed signature: 73ec7028309164ac64e10cd35d8492ce
// flow-typed version: <<STUB>>/deep-extend_v^0.4.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-extend/lib/deep-extend' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-extend/index' {
  declare module.exports: $Exports<'deep-extend'>;
}
declare module 'deep-extend/index.js' {
  declare module.exports: $Exports<'deep-extend'>;
}
declare module 'deep-extend/lib/deep-extend.js' {
  declare module.exports: $Exports<'deep-extend/lib/deep-extend'>;
}
