// flow-typed signature: dace3448559521160a6174f7205b790d
// flow-typed version: <<STUB>>/lodash.uniqueid_v^4.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.uniqueid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.uniqueid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.uniqueid/index' {
  declare module.exports: $Exports<'lodash.uniqueid'>;
}
declare module 'lodash.uniqueid/index.js' {
  declare module.exports: $Exports<'lodash.uniqueid'>;
}
