// flow-typed signature: 0a6b09f8c7a4269668053d5ef8f58396
// flow-typed version: <<STUB>>/react-datetime_v^2.7.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datetime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datetime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datetime/DateTime' {
  declare module.exports: any;
}

declare module 'react-datetime/dist/react-datetime' {
  declare module.exports: any;
}

declare module 'react-datetime/dist/react-datetime.min' {
  declare module.exports: any;
}

declare module 'react-datetime/src/DaysView' {
  declare module.exports: any;
}

declare module 'react-datetime/src/MonthsView' {
  declare module.exports: any;
}

declare module 'react-datetime/src/onClickOutside' {
  declare module.exports: any;
}

declare module 'react-datetime/src/TimeView' {
  declare module.exports: any;
}

declare module 'react-datetime/src/YearsView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datetime/DateTime.js' {
  declare module.exports: $Exports<'react-datetime/DateTime'>;
}
declare module 'react-datetime/dist/react-datetime.js' {
  declare module.exports: $Exports<'react-datetime/dist/react-datetime'>;
}
declare module 'react-datetime/dist/react-datetime.min.js' {
  declare module.exports: $Exports<'react-datetime/dist/react-datetime.min'>;
}
declare module 'react-datetime/src/DaysView.js' {
  declare module.exports: $Exports<'react-datetime/src/DaysView'>;
}
declare module 'react-datetime/src/MonthsView.js' {
  declare module.exports: $Exports<'react-datetime/src/MonthsView'>;
}
declare module 'react-datetime/src/onClickOutside.js' {
  declare module.exports: $Exports<'react-datetime/src/onClickOutside'>;
}
declare module 'react-datetime/src/TimeView.js' {
  declare module.exports: $Exports<'react-datetime/src/TimeView'>;
}
declare module 'react-datetime/src/YearsView.js' {
  declare module.exports: $Exports<'react-datetime/src/YearsView'>;
}
