// flow-typed signature: 1ada9f8ed82c47dc55022b67462e32c8
// flow-typed version: <<STUB>>/sprintf.js_v^0.1.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sprintf.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sprintf.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sprintf.js/examples/ex001' {
  declare module.exports: any;
}

declare module 'sprintf.js/examples/ex002' {
  declare module.exports: any;
}

declare module 'sprintf.js/examples/ex003' {
  declare module.exports: any;
}

declare module 'sprintf.js/examples/ex004' {
  declare module.exports: any;
}

declare module 'sprintf.js/examples/ex005' {
  declare module.exports: any;
}

declare module 'sprintf.js/examples/ex006' {
  declare module.exports: any;
}

declare module 'sprintf.js/examples/ex007' {
  declare module.exports: any;
}

declare module 'sprintf.js/lib/convertArgToStr' {
  declare module.exports: any;
}

declare module 'sprintf.js/lib/sprintf' {
  declare module.exports: any;
}

declare module 'sprintf.js/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sprintf.js/examples/ex001.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex001'>;
}
declare module 'sprintf.js/examples/ex002.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex002'>;
}
declare module 'sprintf.js/examples/ex003.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex003'>;
}
declare module 'sprintf.js/examples/ex004.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex004'>;
}
declare module 'sprintf.js/examples/ex005.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex005'>;
}
declare module 'sprintf.js/examples/ex006.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex006'>;
}
declare module 'sprintf.js/examples/ex007.js' {
  declare module.exports: $Exports<'sprintf.js/examples/ex007'>;
}
declare module 'sprintf.js/lib/convertArgToStr.js' {
  declare module.exports: $Exports<'sprintf.js/lib/convertArgToStr'>;
}
declare module 'sprintf.js/lib/sprintf.js' {
  declare module.exports: $Exports<'sprintf.js/lib/sprintf'>;
}
declare module 'sprintf.js/test.js' {
  declare module.exports: $Exports<'sprintf.js/test'>;
}
