export const EDIT_PROJECT_BOUNDS_COMPONENT = 'edit-project-bounds-component'
export const ISOCHRONE_COMPONENT = 'isochrone-component'
export const SCENARIO_COMPONENT = 'scenario-component'
export const SINGLE_POINT_ANALYSIS_COMPONENT = 'single-point-analysis-component'
export const OPPORTUNITY_COMPONENT = 'opportunity-component'
export const REGIONAL_COMPONENT = 'regional-component'
export const REGIONAL_COMPARISON_COMPONENT = 'regional-comparison-component'
export const EDIT_REGIONAL_ANALYSIS_BOUNDS_COMPONENT = 'edit-regional-analysis-bounds-component'
