export const EDIT_PROJECT_BOUNDS_COMPONENT = 'edit-project-bounds-component'
export const ISOCHRONE_COMPONENT = 'isochrone-component'
export const SCENARIO_COMPONENT = 'scenario-component'
export const SINGLE_POINT_ANALYSIS_COMPONENT = 'single-point-analysis-component'
export const OPPORTUNITY_COMPONENT = 'opportunity-component'
