// flow-typed signature: f1711ab2d8b879f4cc4e19b037e8727a
// flow-typed version: <<STUB>>/@conveyal/gridualizer_v^2.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@conveyal/gridualizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@conveyal/gridualizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@conveyal/gridualizer/build/__tests__/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/__tests__/diverging' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/__tests__/equal-interval' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/__tests__/quantile' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/diverging' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/equal-interval' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/jenks' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/classifiers/quantile' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/color-scales' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/colorizers/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/colorizers/dither' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/colorizers/gradient' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/dot' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/grid-tile-layer' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/index' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/interpolators' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/interpolators/bicubic' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/interpolators/bilinear' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/interpolators/nearest' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/mock-data' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/react/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/react/dot' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/react/grid-map-layer' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/scales/__tests__/diverging' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/scales/__tests__/equal-interval' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/scales/__tests__/quantile' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/scales/diverging' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/scales/equal-interval' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/scales/quantile' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/build/util' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/example' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/__tests__/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/dot' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/index' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/mock-data' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/react/choropleth' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/react/dot' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/scales/__tests__/diverging' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/scales/__tests__/equal-interval' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/scales/__tests__/quantile' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/scales/diverging' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/scales/equal-interval' {
  declare module.exports: any;
}

declare module '@conveyal/gridualizer/lib/scales/quantile' {
  declare module.exports: any;
}

// Filename aliases
declare module '@conveyal/gridualizer/build/__tests__/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/__tests__/choropleth'>;
}
declare module '@conveyal/gridualizer/build/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/choropleth'>;
}
declare module '@conveyal/gridualizer/build/classifiers/__tests__/diverging.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/__tests__/diverging'>;
}
declare module '@conveyal/gridualizer/build/classifiers/__tests__/equal-interval.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/__tests__/equal-interval'>;
}
declare module '@conveyal/gridualizer/build/classifiers/__tests__/quantile.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/__tests__/quantile'>;
}
declare module '@conveyal/gridualizer/build/classifiers/diverging.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/diverging'>;
}
declare module '@conveyal/gridualizer/build/classifiers/equal-interval.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/equal-interval'>;
}
declare module '@conveyal/gridualizer/build/classifiers/jenks.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/jenks'>;
}
declare module '@conveyal/gridualizer/build/classifiers/quantile.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/classifiers/quantile'>;
}
declare module '@conveyal/gridualizer/build/color-scales.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/color-scales'>;
}
declare module '@conveyal/gridualizer/build/colorizers/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/colorizers/choropleth'>;
}
declare module '@conveyal/gridualizer/build/colorizers/dither.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/colorizers/dither'>;
}
declare module '@conveyal/gridualizer/build/colorizers/gradient.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/colorizers/gradient'>;
}
declare module '@conveyal/gridualizer/build/dot.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/dot'>;
}
declare module '@conveyal/gridualizer/build/grid-tile-layer.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/grid-tile-layer'>;
}
declare module '@conveyal/gridualizer/build/index.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/index'>;
}
declare module '@conveyal/gridualizer/build/interpolators.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/interpolators'>;
}
declare module '@conveyal/gridualizer/build/interpolators/bicubic.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/interpolators/bicubic'>;
}
declare module '@conveyal/gridualizer/build/interpolators/bilinear.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/interpolators/bilinear'>;
}
declare module '@conveyal/gridualizer/build/interpolators/nearest.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/interpolators/nearest'>;
}
declare module '@conveyal/gridualizer/build/mock-data.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/mock-data'>;
}
declare module '@conveyal/gridualizer/build/react/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/react/choropleth'>;
}
declare module '@conveyal/gridualizer/build/react/dot.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/react/dot'>;
}
declare module '@conveyal/gridualizer/build/react/grid-map-layer.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/react/grid-map-layer'>;
}
declare module '@conveyal/gridualizer/build/scales/__tests__/diverging.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/scales/__tests__/diverging'>;
}
declare module '@conveyal/gridualizer/build/scales/__tests__/equal-interval.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/scales/__tests__/equal-interval'>;
}
declare module '@conveyal/gridualizer/build/scales/__tests__/quantile.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/scales/__tests__/quantile'>;
}
declare module '@conveyal/gridualizer/build/scales/diverging.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/scales/diverging'>;
}
declare module '@conveyal/gridualizer/build/scales/equal-interval.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/scales/equal-interval'>;
}
declare module '@conveyal/gridualizer/build/scales/quantile.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/scales/quantile'>;
}
declare module '@conveyal/gridualizer/build/util.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/build/util'>;
}
declare module '@conveyal/gridualizer/example.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/example'>;
}
declare module '@conveyal/gridualizer/lib/__tests__/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/__tests__/choropleth'>;
}
declare module '@conveyal/gridualizer/lib/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/choropleth'>;
}
declare module '@conveyal/gridualizer/lib/dot.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/dot'>;
}
declare module '@conveyal/gridualizer/lib/index.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/index'>;
}
declare module '@conveyal/gridualizer/lib/mock-data.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/mock-data'>;
}
declare module '@conveyal/gridualizer/lib/react/choropleth.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/react/choropleth'>;
}
declare module '@conveyal/gridualizer/lib/react/dot.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/react/dot'>;
}
declare module '@conveyal/gridualizer/lib/scales/__tests__/diverging.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/scales/__tests__/diverging'>;
}
declare module '@conveyal/gridualizer/lib/scales/__tests__/equal-interval.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/scales/__tests__/equal-interval'>;
}
declare module '@conveyal/gridualizer/lib/scales/__tests__/quantile.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/scales/__tests__/quantile'>;
}
declare module '@conveyal/gridualizer/lib/scales/diverging.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/scales/diverging'>;
}
declare module '@conveyal/gridualizer/lib/scales/equal-interval.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/scales/equal-interval'>;
}
declare module '@conveyal/gridualizer/lib/scales/quantile.js' {
  declare module.exports: $Exports<'@conveyal/gridualizer/lib/scales/quantile'>;
}
